from typing import Type
from pydantic import BaseModel
from google import genai
from google.genai import types
from google.genai.errors import APIError
from app.core.config import settings

class GeminiClient:
    @staticmethod
    def generate_structured_data(
        prompt: str,
        system_instruction: str,
        response_schema: Type[BaseModel]
    ) -> BaseModel:
        """
        Sends a request to the Gemini API and parses the response into the specified Pydantic schema.
        This client remains generic and decoupled from any resume-specific business logic.
        """
        if not settings.GEMINI_API_KEY:
            raise ValueError(
                "Gemini API key is not configured. Please set the GEMINI_API_KEY environment variable."
            )

        # Initialize the Google GenAI client with our key
        client = genai.Client(api_key=settings.GEMINI_API_KEY)
        
        # Load model name from configuration
        model_name = settings.GEMINI_MODEL or "gemini-2.5-flash"

        try:
            response = client.models.generate_content(
                model=model_name,
                contents=prompt,
                config=types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    response_mime_type="application/json",
                    response_schema=response_schema,
                    temperature=0.2,  # Lower temperature for more consistent, objective reviews
                )
            )

            if not response.parsed:
                raise ValueError("Response generated by Gemini did not match the expected schema structure.")

            return response.parsed

        except APIError as e:
            raise RuntimeError(f"Gemini API error (code {e.code}): {e.message}")
        except Exception as e:
            raise RuntimeError(f"Gemini service communication error: {str(e)}")
